name: test

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: package
      run: |
        touch bbb1.txt
        echo `pwd`
        echo `ls -a`

    - name: commit and push
      run: |
        echo `pwd`
        echo `ls -a`
        cd ../../
        git clone https://github.com/Fixfly-SS/MpvKit.git
        cd MpvKit
        mv ../test/test/bbb1.txt ./
        git remote set-url origin https://Fixfly-SS:$GH_TOKEN@github.com/Fixfly-SS/MpvKit.git
        git add .
        git commit -m 'add build aritifacts'
        git push origin main
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
