name: test

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: package
      run: |
        touch aaa.txt
        echo 'aaa' > aaa.txt
        echo `pwd`
        echo `ls -a`

    - name: commit and push
      run: |
        echo `pwd`
        echo `ls -a`
        cd ../../
        git clone git@github.com:Fixfly-SS/MpvKit.git
        cd MpvKit
        mv ../test/test/aaa.txt ./
        git config --global user.name 'Fixfly'
        git config --global user.email 'fixfly-1010@fixfly.com'
        git add .
        git commit -m 'add build aritifacts'
        git push origin main
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
